export const validEnv = (overrides: Record<string, string | undefined> = {}) => ({
  NODE_ENV: "test",
  PUBLIC_URL: "https://flow.example.com",
  PORT: "3000",
  DATABASE_PATH: ":memory:",
  TELEGRAM_BOT_TOKEN: "123456:test-token",
  TELEGRAM_WEBHOOK_SECRET: "telegram-secret",
  TELEGRAM_ADMIN_IDS: "123,456",
  GITHUB_APP_ID: "42",
  GITHUB_APP_PRIVATE_KEY_BASE64: Buffer.from("test-private-key").toString("base64"),
  GITHUB_WEBHOOK_SECRET: "github-secret",
  OPENAI_API_KEY: "openai-test-key",
  ANTHROPIC_API_KEY: "anthropic-test-key",
  FLOW_BUILDER: "codex",
  FLOW_REVIEWER: "claude",
  FLOW_MAX_ISSUE_COST_USD: "25",
  FLOW_MAX_FIX_ROUNDS: "2",
  ...overrides,
});
